config/routes.rb
Rails.application.routes.draw do
  resources :trades do
    resources :replies, only: [:create, :destroy]
    collection do
      get 'clothes'
      get 'books'
      get 'rests'
    end
  end
  devise_for :users
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reply.rb
class Reply < ApplicationRecord
  belongs_to :user
  belongs_to :trade
end

app/models/trade.rb
class Trade < ApplicationRecord
  belongs_to :user
  has_many :replies, dependent: :destroy
  mount_uploader :image, ImageUploader
  validates :title, presence: :true, length: { maximum: 50 }
  validates :content, presence: :true, length: { minimum: 5 }
  validates :image, presence: :true
  validates :kakaoid, presence: :true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :replies
  has_many :trades
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_locale
 
  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  def create
    if @reply = Reply.create(reply_params)
      flash['notice'] = '댓글이 작성되었습니다'
      redirect_to trade_path(@reply.trade)
    else
      flash['danger'] = '댓글을 다시 작성하세요'
      redirect_to trade_path(@reply.trade)
    end
  end

  def destroy
    @reply = Reply.find(params[:id])
    if @reply.destroy
      flash['notice'] = '댓글이 삭제되었습니다'
      redirect_to trade_path(@reply.trade)
    else
      flash['danger'] = '댓글을 다시 삭제하세요'
      redirect_to trade_path(@reply.trade)
    end
  end
  private
  def reply_params
    params.require(:reply).permit(:content,:trade_id, :user_id)
  end
end

app/controllers/trades_controller.rb
class TradesController < ApplicationController
  before_action :find_trade, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: :index
  
  def clothes
    @trade_per_page = 12
    @clothes = Trade.order(id: :desc).where(:variety => '옷').page(params[:page]).per(@trade_per_page)
    @clothes_length = Trade.order(id: :desc).where(:variety => '옷').length
    @page = params[:page].to_i
  end
  def books
    @trade_per_page = 12
    @books = Trade.order(id: :desc).where(:variety => '책').page(params[:page]).per(@trade_per_page)
    @books_length = Trade.order(id: :desc).where(:variety => '책').length
    @page = params[:page].to_i
  end
  def rests
    @trade_per_page = 12
    @rests = Trade.order(id: :desc).where(:variety => '기타').page(params[:page]).per(@trade_per_page)
    @rests_length = Trade.order(id: :desc).where(:variety => '기타').length
    @page = params[:page].to_i
  end
  def index
    @trades = Trade.order(created_at: :DESC).page(params[:page]).per(16)
  end

  def show
    # TODO: 댓글 달기
    @reply = Reply.new
    @replies = @trade.replies
  end

  def new
    @trade = Trade.new
  end
  def create
    @trade = Trade.new(trade_params)
    if @trade.save
      flash['notice'] = '게시글이 작성되었습니다'
      redirect_to trade_path(@trade.id)
    else
      flash['danger'] = '5자 이상의 글과 사진이 필요합니다' 
      redirect_to new_trade_path
    end
  end

  def edit
  end
  def update
    if @trade.update(trade_params)
      flash['notice'] = '게시글이 수정되었습니다'
      redirect_to trade_path(@trade)
    else
      flash['danger'] = '5자 이상의 글과 사진이 필요합니다'
      redirect_to edit_trade_path(@trade)
    end
  end
  def destroy
    if @trade.destroy
      flash['notice'] = '게시글이 삭제되었습니다'
      redirect_to trades_path
    else
      flash['danger'] = '게시글을 다시 삭제하세요'
      redirect_to trade_path(@trade)
    end
  end
  
  private
    def trade_params
      params.require(:trade).permit(:title, :content, :kakaoid,:user_id, :variety, :image) 
    end
    def find_trade
      @trade = Trade.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def bootstrap_msg type
        result = case type
            when 'notice' then 'success'
            when 'alert' then 'warning'
            when 'danger' then 'danger'
            else 'info'
            end
    end 
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/trades_helper.rb
module TradesHelper
end

app/views/home/index.html.erb
<header class="masthead text-center text-white d-flex">
  <div class="container my-auto">
    <div class="row mt-5">
      <div class="col-lg-10 mx-auto pt-5">
        <h1 class="text-uppercase text-primary">
          <strong>수선화 안녕?</strong>
        </h1>
        <hr>
      </div>
      <div class="col-lg-8 mx-auto">
        <p class="text-faded mb-5 text-dark">남산고 학생들에 의해 남산고 학생들을 위해 운영되는 <br>이곳은 대구남산고등학교 학생커뮤니티입니다.</p>
        <a class="btn btn-primary btn-xl js-scroll-trigger" href="#about">반가워요</a>
      </div>
    </div>
  </div>
</header>

<section class="bg-primary" id="about">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 mx-auto text-center">
        <h2 class="section-heading text-white">수선화 안녕?</h2>
        <hr class="light my-4">
        <p class="text-faded mb-4">
           이 곳은 남산고등학교 학생들의 편의를 위한 남산고 커뮤니티입니다.<br/>
           옷,책,기타로 나뉜 섹션에서 물물교환(거래)를 할 수 있습니다.<br/>
           모두들 서로를 먼저 생각하는 수선인이 됩시다.
        </p>
        <a class="btn btn-light btn-xl js-scroll-trigger" href="#services">Join us</a>
      </div>
    </div>
  </div>
</section>

<section id="services">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h2 class="section-heading">물물장터</h2>
        <p class="text-muted mb-0">학생들끼리 물건을 교환하는 곳입니다.</p>
        <hr class="my-4">
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-sm-4 text-center">
        <div class="service-box mt-5 mx-auto">
          <i class="fa fa-4x fa-shopping-bag text-primary mb-3 sr-icons"></i>
          <h3 class="mb-3">옷</h3>
          <p class="text-muted mb-0">교복과 체육복 교환을 추천합니다</p>
        </div>
      </div>
      <div class="col-sm-4 text-center">
        <div class="service-box mt-5 mx-auto">
          <i class="fa fa-4x fa-book text-primary mb-3 sr-icons"></i>
          <h3 class="mb-3">책</h3>
          <p class="text-muted mb-0">교과서나 문제집 교환을 추천합니다</p>
        </div>
      </div>
      <div class="col-sm-4 text-center">
        <div class="service-box mt-5 mx-auto">
          <i class="fa fa-4x fa-spinner text-primary mb-3 sr-icons"></i>
          <h3 class="mb-3">기타</h3>
          <p class="text-muted mb-0">필기구, 악세서리 등 창의성을 발휘해봅시다</p>
        </div>
      </div>
    </div>
  </div>
</section>


<section class="bg-primary text-white">
  <div class="container">
    <h3 class="mb-4 text-center">깨끗한 커뮤니티를 위한 규칙</h3>
    <ol class="">
      <li>원가의 90% 이하로 물건을 팔아야 한다</li>
      <li>무조건 직거래만 할 수 있다</li>
      <li>게시물 제목은 `학반번호 교환하고자 하는 물건'이어야 한다</li>
      <li>게시물을 쓸 때 카카오톡 아이디를 적어야 한다</li>
      <li>남을 먼저 생각하며 깨끗한 언어생활을 한다</li>
    </ol>
  </div>
</section>

<section class="">
  <div class="container">
    <h1 class="mb-4 text-center font-weight-bold">S-CYCLE</h1>
    <h3 class="text-center">nam<strong>S</strong>an고등학교에서 <strong>S</strong>useon인들이 물건을 reu<strong>S</strong>e한다</h3>
    <img src="s-cycle.png" alt="s-cycle" class="img-fluid mx-auto d-block mt-5">
  </div>
</section>


<section id="contact" class="bg-primary text-white">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 mx-auto text-center">
        <h2 class="section-heading">문의하기</h2>
        <hr class="my-4">
        <p class="mb-5">문의하실거에요?</p>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-4 ml-auto text-center">
        <i class="fa fa-comment fa-3x mb-3 sr-contact"></i><br/>
            <img src="id_type.png" width="140px"/>
      </div>
      <div class="col-lg-4 mr-auto text-center mt-3">
        <i class="fa fa-envelope-o fa-3x mb-3 sr-contact"></i>
        <p>
          hellonamsan@naver.com
        </p>
      </div>
    </div>
  </div>
</section>

    <!-- Bootstrap core JavaScript -->
    <!--<script src="vendor/jquery/jquery.min.js"></script>-->
    <!--<script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>-->

    <!-- Plugin JavaScript -->
    <!--<script src="vendor/jquery-easing/jquery.easing.min.js"></script>-->
    <!--<script src="vendor/scrollreveal/scrollreveal.min.js"></script>-->
    <!--<script src="vendor/magnific-popup/jquery.magnific-popup.min.js"></script>-->

    <!-- Custom scripts for this template -->
    <!--<script src="js/creative.min.js"></script>-->

app/views/layouts/_flash_message.html.erb
<% flash.each do |msg_type, msg| %>
    <% type = bootstrap_msg(msg_type) %>
    <%= content_tag(:div, msg, class: "container alert alert-#{type} mt-4") %>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary w-100" id="MainNav">
  <%= link_to "수선화안녕", root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item active">
        <%= link_to "물물장터", trades_path, class: "nav-link mr-4" %>
      </li>
      
      <li class="nav-item active">
        <%= link_to "옷", clothes_trades_path, class: "nav-link mr-4" %>
      </li>
      
      <li class="nav-item active">
        <%= link_to "책", books_trades_path, class: "nav-link mr-4" %>
      </li>
      
      <li class="nav-item active">
        <%= link_to "기타", rests_trades_path, class: "nav-link mr-4" %>
      </li>
      
      <% if current_user.nil? %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to current_user.name, edit_user_registration_path, class: "nav-link" %>
        </li>
      <% end %>
      
      
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>수선화안녕</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta charset="utf-8">
    <link rel="icon" href="../flower.png" type="image/gif" sizes="16x16">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="canonical" href="http://www.수선화안녕.com/">
    <meta name="description" content="남산고 학생들에 의해 남산고 학생들을 위해 운영되는 이곳은 대구남산고등학교 학생커뮤니티입니다." />
    <meta property="og:url" content="http://www.수선화안녕.com" />
    <meta property="og:title" content="수선화안녕" />
    <meta property="og:description" content="남산고 학생들에 의해 남산고 학생들을 위해 운영되는 이곳은 대구남산고등학교 학생커뮤니티입니다." />
    <meta property="og:image" content="http://www.수선화안녕.com/daffodill.png" />
    <meta name="robots" content="index,follow" />
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div style="height:56px;"></div>
    <%= render 'layouts/flash_message' %>
    <%= yield %>
  </body>
</html>

app/views/replies/_create.html.erb
<div class="row">
    <%= form_for([@trade,@reply], html: { class: "w-100 mx-3"}) do |c| %>
        <%= c.hidden_field :user_id, value: current_user.id %>
        <%= c.hidden_field :trade_id, value: @trade.id %>
        <%= c.label :content %>
        <div class="form-group cal-10">
           
            <%= c.text_field :content, class: "form-control" %>
        </div>
        <div class="form-group cal-2">
            <%= button_to "댓글", trade_replies_path(@trade,@reply), method: :post, class: "btn btn-primary" %>
        </div>
    <% end %>
</div>

app/views/replies/_index.html.erb
<% @replies.each do |c| %>
    <div class="row align-items-center mb-2">
        <p class="col-10 pl-3 text-left text-dark">
            <%= c.content %>
        </p>
        <% if current_user.id == c.user.id %>
            <span class="col-2">
                <%= button_to "삭제", trade_reply_path(@trade,c),method: :delete,class: "btn btn-danger",data: {confirm: "정말 삭제하겠습니까?"} %>
            </span>
        <% end %>
    </div>
<% end %>

app/views/trades/books.html.erb
<div class="container mt-5">
    <div class="row">
        <% @books.each do |c| %>
            <div class="col-12 col-md-6 col-lg-4 col-xl-3">
                <div class="card my-2" >
                  <!--<img class="card-img-top" src="..." alt="Card image cap">-->
                  <%= image_tag c.image.thumb, class: "card-img-top"  %>
                  <div class="card-body">
                    <h5 class="card-title"><%= c.title.first(15) %></h5>
                    <h5 class="text-muted">@<%= c.kakaoid %></h5>
                    <%= link_to "Show", trade_path(c), class: "btn btn-primary" %>
                  </div>
                </div>
            </div>
        <% end %>
    </div>
    <div class="row justify-content-center align-items-center">
        <%= paginate @books, theme: 'twitter-bootstrap-4'%>
    </div>
</div>

app/views/trades/clothes.html.erb
<div class="container mt-5">
    <div class="row">
        <% @clothes.each do |c| %>
            <div class="col-12 col-md-6 col-lg-4 col-xl-3">
                <div class="card my-2" >
                  <!--<img class="card-img-top" src="..." alt="Card image cap">-->
                  <%= image_tag c.image.thumb, class: "card-img-top"  %>
                  <div class="card-body">
                    <h5 class="card-title"><%= c.title.first(15) %></h5>
                    <h5 class="text-muted">@<%= c.kakaoid %></h5>
                    <%= link_to "Show", trade_path(c), class: "btn btn-primary" %>
                  </div>
                </div>
            </div>
        <% end %>
    </div>
    <div class="row justify-content-center align-items-center">
        <%= paginate @clothes, theme: 'twitter-bootstrap-4'%>
    </div>
</div>

app/views/trades/edit.html.erb
<div class="container mt-5">
    <%= form_for(@trade, html: { multipart: true }) do |c| %>
        <%= c.hidden_field :user_id, value: current_user.id %>
        <div class="form-group">
            <%= t 'views.trade.variety' %><br/>
            <%= c.select :variety, ['옷', '책', '기타'] %>
        </div>
        <div class="form-group">
            <%= t 'views.trade.title' %>
            <%= c.text_field :title, class: "form-control" %>
        </div>
        <div class="form-group">
            <%= t 'views.trade.kakaoid' %>
            <%= c.text_field :kakaoid, class: "form-control" %>
        </div>
        <div class="form-group">
            <%= t 'views.trade.content' %>
            <%= c.text_area :content, :class => "tinymce", :rows => 20, :cols => 120 %>
            <%= tinymce %>
        </div>
        <div class="form-group">
            <%= t 'views.trade.image'%>
            <%=c.file_field(:image, accept: 'image/*', class: 'form-control', onchange: "picChange(event)") %>
        </div>
        <div class="form-group">
            <%= button_to "수정하기", trade_path, method: :patch, class: "btn btn-primary" %>
        </div>
    <% end %>
</div>

app/views/trades/index.html.erb
<header class="w-100 header-card">
    <div class="container h-100 d-flex flex-column justify-content-center">
      <div class="d-flex flex-row justify-content-between">
        <h2>물물장터</h2>
        <p align="right">
          <%= link_to "글쓰기", new_trade_path, class: "btn btn-primary" %>
        </p>
        
      </div>
    </div>
</header>

<div class="container mt-5">
    <div class="row">
        <% @trades.each do |c| %>
            <div class="col-12 col-md-6 col-lg-4 col-xl-3">
                <div class="card my-2" >
                  <!--<img class="card-img-top" src="..." alt="Card image cap">-->
                  <%= image_tag c.image.thumb, class: "card-img-top"  %>
                  <div class="card-body">
                    <h5 class="card-title"><%= c.title.first(15) %></h5>
                    <h5 class="text-muted">@<%= c.kakaoid %></h5>
                    <%= link_to "Show", trade_path(c), class: "btn btn-primary" %>
                  </div>
                </div>
            </div>
        <% end %>
    </div>
    <div class="row justify-content-center align-items-center">
        <%= paginate @trades, theme: 'twitter-bootstrap-4'%>
    </div>
</div>

app/views/trades/new.html.erb
<div class="container mt-5">
    <%= form_for(@trade, html: { multipart: true }) do |c| %>
        <%= c.hidden_field :user_id, value: current_user.id %>
        <div class="form-group">
            <%= t 'views.trade.variety' %><br/>
            <%= c.select :variety, ['옷', '책', '기타'] %>
        </div>
        <div class="form-group">
            <%= t 'views.trade.title' %>
            <%= c.text_field :title, class: "form-control" %>
        </div>
        <div class="form-group">
            <%= t 'views.trade.kakaoid' %>
            <%= c.text_field :kakaoid, class: "form-control" %>
        </div>
        <div class="form-group">
            <%= t 'views.trade.content' %>
            <%= c.text_area :content, :class => "tinymce", :rows => 20, :cols => 120 %>
            <%= tinymce %>
        </div>
        <div class="form-group">
            <%= t 'views.trade.image'%>
            <%=c.file_field(:image, accept: 'image/*', class: 'form-control', onchange: "picChange(event)") %>
        </div>
        <div class="form-group">
            <%= button_to "글쓰기", trades_path, method: :post, class: "btn btn-primary" %>
        </div>
    <% end %>
</div>

app/views/trades/rests.html.erb
<div class="container mt-5">
    <div class="row">
        <% @rests.each do |c| %>
            <div class="col-12 col-md-6 col-lg-4 col-xl-3">
                <div class="card my-2" >
                  <!--<img class="card-img-top" src="..." alt="Card image cap">-->
                  <%= image_tag c.image.thumb, class: "card-img-top"  %>
                  <div class="card-body">
                    <h5 class="card-title"><%= c.title.first(15) %></h5>
                    <h5 class="text-muted">@<%= c.kakaoid %></h5>
                    <%= link_to "Show", trade_path(c), class: "btn btn-primary" %>
                  </div>
                </div>
            </div>
        <% end %>
    </div>
    <div class="row justify-content-center align-items-center">
        <%= paginate @rests, theme: 'twitter-bootstrap-4'%>
    </div>
</div>

app/views/trades/show.html.erb
<%# TODO: show 액션 만들기%>
<div class="container mt-5">
  <div class="card">
    <div class="card-body">
      <h1 class="card-title text-center"><%= @trade.title %></h1>
      <h4 class="text-muted text-right">연락할 카카오 Id : @<%= @trade.kakaoid %></h4>
      <h6 class="text-muted text-right"><%= @trade.created_at%></h6>
      <%= image_tag @trade.image, class: "w-100" %>
      <p class="card-text"><%= @trade.content.html_safe %></p>
      <% if current_user.id == @trade.user.id %>
        <%= link_to fa_icon("pencil", text: "수정하기"), edit_trade_path(@trade), class: "btn btn-warning text-white" %>
        <%= link_to fa_icon("trash", text: "삭제하기"), trade_path(@trade), method: :delete,class: "btn btn-danger", data: {confirm: "정말 삭제하겠습니까?"} %>
      <% end %>
    </div>
    <div class="card-footer text-muted text-right bg-white">
      <%= render 'replies/create' %>
      <%= render 'replies/index' %>
    </div>
  </div>
</div>